name: forgejo-runner

services:
  app:
    image: code.forgejo.org/forgejo/runner:6.2.2
    restart: unless-stopped
    command: forgejo-runner daemon
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    volumes:
      - forgejo-runner-data:/data
    networks:
      - public
      - private
    depends_on:
      - dind

  dind:
    image: docker:dind
    restart: unless-stopped
    privileged: true
    command: dockerd -H tcp://0.0.0.0:2375 --tls=false
    networks:
      - private

volumes:
  forgejo-runner-data:
    external: true

networks:
  public:
    external: true
  private:
    driver: bridge
